stderr of test 'python-explain.Bug-3380` in directory 'sql/test/BugTracker-2013` itself:


# 10:49:58 >  
# 10:49:58 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "mapi_open=true" "--set" "mapi_port=35283" "--set" "mapi_usock=/var/tmp/mtest-1162/.s.monetdb.35283" "--set" "monet_prompt=" "--forcemito" "--set" "mal_listing=2" "--dbpath=/ufs/sjoerd/Monet-stable/var/MonetDB/mTests_sql_test_BugTracker-2013" "--set" "mal_listing=0"
# 10:49:58 >  



# 10:49:58 >  
# 10:49:58 >  "Done."
# 10:49:58 >  

