stderr of test 'table-udf-on-remote.Bug-6971` in directory 'sql/test/BugTracker-2020` itself:


# 11:17:10 >  
# 11:17:10 >  "/usr/bin/python3.8" "table-udf-on-remote.Bug-6971.py" "table-udf-on-remote.Bug-6971"
# 11:17:10 >  

# builtin opt 	gdk_dbpath = /home/ferreira/repositories/MonetDB-octbugs/BUILD/var/monetdb5/dbfarm/demo
# builtin opt 	mapi_port = 50000
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# builtin opt 	raw_strings = false
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	mapi_listenaddr = all
# cmdline opt 	mapi_port = 53979
# cmdline opt 	mapi_usock = /var/tmp/mtest-40340/.s.monetdb.53979
# cmdline opt 	gdk_dbpath = /tmp/tmplz1i_wxc/node1/node1
# builtin opt 	gdk_dbpath = /home/ferreira/repositories/MonetDB-octbugs/BUILD/var/monetdb5/dbfarm/demo
# builtin opt 	mapi_port = 50000
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# builtin opt 	raw_strings = false
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	mapi_listenaddr = all
# cmdline opt 	mapi_port = 54689
# cmdline opt 	mapi_usock = /var/tmp/mtest-40340/.s.monetdb.54689
# cmdline opt 	gdk_dbpath = /tmp/tmplz1i_wxc/node2/node2

# 11:17:12 >  
# 11:17:12 >  "Done."
# 11:17:12 >  

