stderr of test 'transaction_with_unreleased_savepoint.Bug-7022` in directory 'sql/test/BugTracker-2020` itself:


# 14:14:39 >  
# 14:14:39 >  "mclient" "-lsql" "-ftest" "-tnone" "-Eutf-8" "-i" "-e" "--host=/var/tmp/mtest-162442" "--port=32313"
# 14:14:39 >  

MAPI  = (monetdb) /var/tmp/mtest-162442/.s.monetdb.32313
QUERY = create table savepointtest (id int, primary key(id));
ERROR = !CREATE TABLE: name 'savepointtest' already in use
CODE  = 42S01
MAPI  = (monetdb) /var/tmp/mtest-162442/.s.monetdb.32313
QUERY = create table savepointtest (id int, primary key(id));
ERROR = !CREATE TABLE: name 'savepointtest' already in use
CODE  = 42S01

# 14:14:40 >  
# 14:14:40 >  "Done."
# 14:14:40 >  

