stderr of test 'local_replica_table_not_detected.Bug-6620` in directory 'sql/test/BugTracker-2018` itself:


# 15:25:58 >  
# 15:25:58 >  "/usr/local/opt/python@2/bin/python2.7" "local_replica_table_not_detected.Bug-6620.py" "local_replica_table_not_detected.Bug-6620"
# 15:25:58 >  


# 15:26:00 >  
# 15:26:00 >  "Done."
# 15:26:00 >  

