stderr of test 'remote-table-where-not-equal.Bug-6621` in directory 'sql/test/BugTracker-2018` itself:


# 18:29:55 >  
# 18:29:55 >  "/usr/local/opt/python@2/bin/python2.7" "remote-table-where-not-equal.Bug-6621.py" "remote-table-where-not-equal.Bug-6621"
# 18:29:55 >  


# 18:29:57 >  
# 18:29:57 >  "Done."
# 18:29:57 >  

