stderr of test 'table_functions_fail_after_restart.Bug-3063` in directory 'sql/test/BugTracker-2012` itself:


# 17:17:38 >  
# 17:17:38 >  "/usr/bin/python3.9" "table_functions_fail_after_restart.Bug-3063.py" "table_functions_fail_after_restart.Bug-3063"
# 17:17:38 >  


# 17:17:40 >  
# 17:17:40 >  "Done."
# 17:17:40 >  

