stderr of test 'python3_dec38` in directory 'sql/test/mapi` itself:


# 18:07:10 >  
# 18:07:10 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "mapi_open=true" "--set" "mapi_port=31922" "--set" "mapi_usock=/var/tmp/mtest-28749/.s.monetdb.31922" "--set" "monet_prompt=" "--forcemito" "--set" "mal_listing=2" "--dbpath=/ufs/manegold/_/Monet/HG/dec38/prefix/--disable-debug_--enable-assert_--enable-optimize/var/MonetDB/mTests_sql_test_mapi" "--set" "mal_listing=0"
# 18:07:10 >  


# 18:07:10 >  
# 18:07:10 >  "Done."
# 18:07:10 >  

